// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class LuaLightUserdata : LuaObject
{
	public new static readonly StringName ClassName = "LuaLightUserdata";

	public LuaLightUserdata() : base(ClassName)
	{
	}
	protected LuaLightUserdata(StringName @class) : base(@class)
	{
	}
	protected LuaLightUserdata(Variant variant) : base(variant)
	{
	}
	protected LuaLightUserdata([NotNull] RefCounted @object) : base(@object)
	{
	}

	public static implicit operator RefCounted(LuaLightUserdata self) => self?._object;
	public static implicit operator Variant(LuaLightUserdata self) => self?._object;
	public static explicit operator LuaLightUserdata(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;
}
