// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class LuaUserdata : LuaTable
{
	public LuaUserdata() : base(NativeName)
	{
	}
	protected LuaUserdata(StringName @class) : base(@class)
	{
	}
	protected LuaUserdata(Variant variant) : base(variant)
	{
	}
	protected LuaUserdata([NotNull] RefCounted @object) : base(@object)
	{
	}

	public static implicit operator RefCounted(LuaUserdata self) => self?._object;
	public static implicit operator Variant(LuaUserdata self) => self?._object;
	public static explicit operator LuaUserdata(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : LuaTable.PropertyName
	{

	}

	public new class MethodName : LuaTable.MethodName
	{

	}

	public new class SignalName : LuaTable.SignalName
	{

	}

	private static readonly StringName NativeName = "LuaUserdata";
}
